name: GradleCICDTemplate
on:
  pull_request:
    branches: ["main"]
jobs:
  checkstyle:
    name: Checkstyle
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout package
        uses: actions/checkout@v4

      - name: Read Checkstyle version from gradle.properties
        id: load_version
        run: |
          CHECKSTYLE_VERSION=$(grep "^checkstyle.version=" gradle.properties | cut -d'=' -f2)
          echo "checkstyle_version=$CHECKSTYLE_VERSION" >> $GITHUB_OUTPUT

      - name: Run Checkstyle
        uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          checkstyle_config: './config/checkstyle/checkstyle.xml'
          level: error
          checkstyle_version: ${{ steps.load_version.outputs.checkstyle_version }}
          fail_level: error
  code_coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Coverage Check
        run: |
          chmod +x gradlew
          ./gradlew testCoverage

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.2
        with:
          paths: |
            ${{ github.workspace }}/**/build/reports/jacoco/prodNormalDebugCoverage/prodNormalDebugCoverage.xml,
            ${{ github.workspace }}/**/build/reports/jacoco/**/debugCoverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 75
          min-coverage-changed-files: 75 error